# fly.toml file generated for irc-on-fly on 2023-02-13T19:56:21+01:00

app = "irc-on-fly"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]

[[services]]
  # openssh-server
  internal_port = 2222
  protocol = "tcp"

  [[services.ports]]
    port = "2222"

[[services]]
  # weechat relay
  internal_port = 9001
  protocol = "tcp"

  [[services.ports]]
    port = "9001"
    handlers = ["tls", "http"]

[[services]]
  # glowing bear via nginx
  http_checks = []
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
